version: 0.2

phases:
  pre_build:
    commands:
      - npm install react-draft-wysiwyg --forced
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id={E1JCQX6Q5R4J8A} --paths '/*'


artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build