export const languages = [
  { language: "Chinese_Simplified", code: "zh" },
  { language: "Chinese_Traditional", code: "zh-TW" },
  { language: "English", code: "en" },
  { language: "Japanese", code: "ja" },
  { language: "Korean", code: "ko" },

  //   Afrikaans: "af",
  //   Albanian: "sq",
  //   Amharic: "am",
  //   Arabic: "ar",
  //   Armenian: "hy",
  //   Azerbaijani: "az",
  //   Bengali: "bn",
  //   Bosnian: "bs",
  //   Bulgarian: "bg",
  //   Catalan: "ca",
  //   Croatian: "hr",
  //   Czech: "cs",
  //   Danish: "da",
  //   Dari: "fa-AF",
  //   Dutch: "nl",
  //   Estonian: "et",
  //   Farsi_Persian: "fa",
  //   Filipino_Tagalog: "tl",
  //   Finnish: "fi",
  //   French: "fr",
  //   French_Canada: "fr-CA",
  //   Georgian: "ka",
  //   German: "de",
  //   Greek: "el",
  //   Gujarati: "gu",
  //   Haitian_Creole: "ht",
  //   Hausa: "ha",
  //   Hebrew: "he",
  //   Hindi: "hi",
  //   Hungarian: "hu",
  //   Icelandic: "is",
  //   Indonesian: "id",
  //   Irish: "ga",
  //   Italian: "it",
  //   Kannada: "kn",
  //   Kazakh: "kk",
  //   Latvian: "lv",
  //   Lithuanian: "lt",
  //   Macedonian: "mk",
  //   Malay: "ms",
  //   Malayalam: "ml",
  //   Maltese: "mt",
  //   Marathi: "mr",
  //   Mongolian: "mn",
  //   Norwegian: "no",
  //   Pashto: "ps",
  //   Polish: "pl",
  //   Portuguese_Brazil: "pt",
  //   Portuguese_Portugal: "pt-PT",
  //   Punjabi: "pa",
  //   Romanian: "ro",
  //   Russian: "ru",
  //   Serbian: "sr",
  //   Sinhala: "si",
  //   Slovak: "sk",
  //   Slovenian: "sl",
  //   Somali: "so",
  //   Spanish: "es",
  //   Spanish_Mexico: "es-MX",
  //   Swahili: "sw",
  //   Swedish: "sv",
  //   Tamil: "ta",
  //   Telugu: "te",
  //   Thai: "th",
  //   Turkish: "tr",
  //   Ukrainian: "uk",
  //   Urdu: "ur",
  //   Uzbek: "uz",
  //   Vietnamese: "vi",
  //   Welsh: "cy",
];
